### ISSUE TITLE
Feature Request: Show the precise date instead of a relative date for posts and comments

### ISSUE THREAD

**Issue by dtantono** [ArthurHeitmann/photon-reddit#10]
Hi
Is it possible to add a new toggle settings to Show the precise date (i.e: Sun Nov 16 20:14:56 2014 UTC) instead of a relative date (i.e: 7 days ago), for posts and comments?

**Comment by ArthurHeitmann** [comment]
If you hover your mouse over the relative date, it will show the absolute time in your local time zone. Or do you still want it as a permanent switch?

**Comment by dtantono** [comment]
I think a permanent switch on the settings will be nice

**Comment by ArthurHeitmann** [comment]
Ok, I'll add it in the next update

**Comment by ArthurHeitmann** [comment]
Update is live
