### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by dnet890** [ArthurHeitmann/photon-reddit#11]
Hi
I tried to login. But, it does not worked. What do you think?
![image](https://github.com/user-attachments/assets/3370421f-bb9e-4c4b-bd52-28c13341f1a6)

**Comment by ArthurHeitmann** [comment]
That's weird

- When you normally visit reddit.com, are you already logged in?
- What exactly did you click to land where you are?
- Please share the url on which you landed

**Comment by dnet890** [comment]
it looks like I Just need to clear the cache and it works again
