### ISSUE TITLE
Feature Request: Upload image/GIF and embed/insert URLs on selected text in the comment section

### ISSUE THREAD

**Issue by dnet890** [ArthurHeitmann/photon-reddit#12]
Hi
Is it possible to upload image/GIF and embed/insert URLs on selected text in the comment section like normal reddit does?

**Comment by ArthurHeitmann** [comment]
Generally, if something can be done on old.reddit.com, it can be implemented in a 3rd party app. From my testing, it's not possible to insert gifs or upload images to comments, outside the official reddit website.

To insert an URL you can use markdown:

`[google](https://google.com/)`  
turns into  
[google](https://google.com/)

Full guide on markdown: https://www.reddit.com/r/reddit.com/wiki/markdown
