### ISSUE TITLE
Comments without replies taking a lot of space

### ISSUE THREAD

**Issue by TheChilliPL** [ArthurHeitmann/photon-reddit#2]
I think comments without replies shouldn't take up that much space
![image](https://user-images.githubusercontent.com/18823939/127758080-0d9910bc-e7bf-4bea-beb5-6a7565e5c8d1.png)
Google Chrome 92.0.4515.107 @ Windows 11 Insider Program 21H2 22000.71

**Comment by ArthurHeitmann** [comment]
@TheChilliPL I agree. I just don't know what to do with the up/down vote buttons, upvote count, menu button, and minimize bar. Do you have any suggestions?
