### ISSUE TITLE
(Bug)Cannot load archived version

### ISSUE THREAD

**Issue by dtantono** [ArthurHeitmann/photon-reddit#8]
Hi
I want to load archived version button. But, I got this error message. Is this a bug?
<img width="707" alt="image" src="https://github.com/ArthurHeitmann/photon-reddit/assets/29157187/420f61e2-3062-48da-bffe-62ab0db98392">

**Comment by ArthurHeitmann** [comment]
Back when that button worked, it used the pushshift api service to retrieve archived comments. But for almost half a year now pushshift is no longer publicly available, only to some moderators. I'm working on a fix, by using a different service. But that will take some time.

**Comment by ArthurHeitmann** [comment]
Fixed. I'm now using a different API, which should work for now
