### ISSUE TITLE
Feature Request: Mark read on scroll for read post

### ISSUE THREAD

**Issue by dtantono** [ArthurHeitmann/photon-reddit#9]
Hi
I find feature like mark read on scroll is quite beneficial So, there will be some kind of special mark to remember that this kind of post have been read. Is it possible?

**Comment by ArthurHeitmann** [comment]
There already is a setting that will keep track of which posts you have seen. Currently it is only used to hide previously seen posts, if you enable that setting. Or what were you thinking of?

**Comment by dtantono** [comment]
<img width="458" alt="image" src="https://github.com/ArthurHeitmann/photon-reddit/assets/29157187/37bc1ed5-cd95-46a1-82da-9136ef122275">
do you mean this setting? because this setting mark nothing. What kind this setting do?

**Comment by ArthurHeitmann** [comment]
By itself it doesn't do anything. You need to enable "Hide seen posts" right below it, for it to hide posts.

**Comment by dtantono** [comment]
<img width="245" alt="image" src="https://github.com/ArthurHeitmann/photon-reddit/assets/29157187/d09c51e3-11e9-4315-be94-108d97d22330">
I don't really like hiding read post and I prefer subscript or superscript or mark it darker like this. Is it possible?

**Comment by ArthurHeitmann** [comment]
Yes, I can make them darker. I'll add a setting for that in the next update

**Comment by ArthurHeitmann** [comment]
This is how it will look with dark and light theme:

![image](https://github.com/ArthurHeitmann/photon-reddit/assets/37270165/26432446-d466-4795-b74a-e3ff4b1b9d7a)
![image](https://github.com/ArthurHeitmann/photon-reddit/assets/37270165/d873ed52-3813-4678-8447-5c0cd0b08ba9)


![image](https://github.com/ArthurHeitmann/photon-reddit/assets/37270165/79e7bb6a-ff69-4790-8f4b-88747ba5d24d)
![image](https://github.com/ArthurHeitmann/photon-reddit/assets/37270165/20cbdab1-5908-4f5c-9272-1573695160c1)

**Comment by ArthurHeitmann** [comment]
Update is live
